name: CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    strategy:
      matrix:
        include:
          - xcode: "13.4.1"
            ios: "16.2"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Firebase
        run: |
          firebase appcheck:install
          firebase distribution:deploy --token ${{ secrets.FIREBASE_TOKEN }}

