name: Deploy to Firebase

on:
  push:
    branches:
      - firebase-dist

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # build here
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: GitHubActions.ipa
          path: ./build # Path to your IPA file will usually be root of the project (if you use Fastlane)

  distribute-ios:
    needs: build-ios # This is important
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: YourApp.ipa

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_IOS_APP_ID}}
          file: GitHubActions.ipa
          groups: testers
          token: ${{secrets.FIREBASE_TOKEN}}
