name: Deploy to Firebase

on:
  push:
    branches:
      - firebase-dist

jobs:
  deploy:
    runs-on: macos-latest

    env:
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120 # Adjust the timeout value (in seconds) as needed
      FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 5    # Adjust the number of retries as needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Deploy to Firebase
        run: bundle exec fastlane distribute
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Ensure you have this secret set in your repository
