name: Deploy to Firebase

on:
  push:
    branches:
      - firebase-dist

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 3.x # Adjust the Ruby version as needed

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Deploy to Firebase
        run: bundle exec fastlane deploy_to_firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Ensure you have this secret set in your repository
