name: Deploy to Firebase

on:
  push:
    branches:
      - firebase-dist

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a version >=20.0.0

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.FIREBASE_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies
        run: npm install
        working-directory: ./

      - name: Build iOS App
        run: |
          xcodebuild clean build \
            -workspace GitHubActions.xcworkspace \
            -scheme GitHubActions \
            -destination "platform=iOS Simulator,OS=16.2,name=iPhone 11" # Adjust the destination as needed

      - name: Deploy to Firebase App Distribution
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > firebase-service-account.json
          export FIREBASE_ADMIN_CREDENTIALS=$(cat firebase-service-account.json
          firebase appdistribution:distribute ./build/Products/Release-iphoneos/GitHubActions.ipa
        env:
         FIREBASE_CLI_SUPPRESS_PROMPTS: 1
