name: Deploy to Firebase

on:
  push:
    branches:
      - firebase-dist
  workflow_run:
    workflows: ["Manual Deploy"]
    types:
      - completed
  repository_dispatch:
    types:
      - manual-trigger

jobs:
  deploy:
    runs-on: macos-latest

    env:
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120
      FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use the latest version of the action

      - name: Increment build number
        run: fastlane increment_build_number_fb

      - name: Deploy iOS to Firebase via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: distribute
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          # ... (other environment variables)

      # Add the following steps to set the completion status as an output
      - name: Set workflow status
        id: set_status
        run: echo "##[set-output name=conclusion;]${{ job.status }}"
      
      - name: Fail the workflow on error
        if: failure()
        run: exit 1

# Add a new workflow for manual triggering
# This will run only when manually triggered from GitHub UI
  manual_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Manual deploy triggered
        run: echo "Manual deploy triggered"
