name: Manual Trigger

on:
  workflow_run:
    workflows: ["firebase"]
    types:
      - completed

jobs:
  trigger-firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Firebase Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'firebase.yml',
              ref: 'firebase-dist', // You can specify the branch or tag to trigger the workflow on
              inputs: {
                manual-trigger: 'true'
              }
            });
            console.log(response.data);
